### ISSUE TITLE
homebrew compatibility on macOS

### ISSUE THREAD

**Issue by kevinlawler** [alerque/decasify#22]
desired: `brew install decasify` to get command-line tool

**Comment by alerque** [comment]
I just submitted a formula PR, see above. The catch is that I'm not actually on macOS at all and have limited ability to test this. Can you give it a test build and note your results in the PR?

**Comment by kevinlawler** [comment]
I see:
![shot1](https://github.com/user-attachments/assets/95a47e20-803d-4088-bc45-77852c54841a)
![shot2](https://github.com/user-attachments/assets/bdb1caaa-a48c-4ef5-b66b-649f38728c99)

I think your "O" in "only" is capitalized which is causing an issue, in addition to the other indicated errors.

By the way, I was going to suggest changing from LGPL to BSD/MIT/Apache/* in your closed thread on licenses.

**Comment by alerque** [comment]
I fixed up some of the lint issues but ran into this one. It looks like Homebrew has some lower limits on notability:

> GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)

I don't know if there is any room for discretion from Homebrew maintainers. If not I'm happy to see a formula hosted elsewhere that can be built by those that really want it. In the mean time spread the word I guess.

**Comment by kevinlawler** [comment]
Marketing side quest. That is in fact a new one.

**Comment by alerque** [comment]
@kevinlawler If it turns out they won't accept it based on notoriety I'll look into a tap or whatever it is that would enable a side-loaded package.

In the mean time I see you've also contributed to Neovide. Did you by chance try out the Neovim plugin version of this? It hasn't gone out in a tagged release yet (development was post v0.6.0) but HEAD should work, and that's what most NeoVIM plugin managers do by default anyway.

**Comment by alerque** [comment]
@kevinlawler Can you test build the formula I posted? I'm not actually on macOS and don't have a straight forward way to test it, and it seems it might be throwing some build error. Getting that fixed might help get it through.

**Comment by alerque** [comment]
Nevermind I think I figured out the error and it is passing the self tests now.

**Comment by alerque** [comment]
```console
$ brew install decasify
```

**Comment by kevinlawler** [comment]
Great stuff, I am running live with this

Thank you for your intelligent hard work

**Comment by alerque** [comment]
[![Packaging status](https://repology.org/badge/vertical-allrepos/decasify.svg)](https://repology.org/project/decasify/versions)
